name: fussball_teams
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.4
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocode: ^1.0.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.3.0
  json_serializable: ^6.0.0
  location: ^4.3.0
  path_provider: ^2.0.5
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  synchronized: ^3.0.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sample_data/
    - assets/images/
